//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAuthFace.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblOrders = new HashSet<tblOrder>();
        }
    
        public string customerEmail { get; set; }
        public string customerName { get; set; }
        public string customerPhone { get; set; }
        public int idAutoPK { get; set; }
    
        public virtual ICollection<tblOrder> tblOrders { get; set; }
    }
}
